name: CI - train and save models

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]

jobs:
  mtx-pipeline:
    name: train and save models
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python: [3.11,3.10]

    steps:
      - name : Checkout
        uses: actions/checkout@v4

      - name: setup python 
        uses: actions/python@v4
        with:
          python-version: $ {{ matrix.python }}

      - name: Upgrade pip
        run: python -m pip install --upgrade pip setuptools wheel

      - name: install project dependencies
        run: python -m pip install -r requirements.txt

      - name: train the models
        run: | 
            python train.py 
            ls -la artifacts

      - name: upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ml-artifact- $ {{ matrix.python }} - ${{ github.run_id }}
          path: artifacts